### ISSUE TITLE
Package license? 

### ISSUE THREAD

**Issue by jbellmore** [bpfz/SharprWowApi#1]
Hello, 

First I would like to say nice work on the project, it seems like a great library!  I would like to possibly fork and submit pull requests against it but I did not see any license version listed. Have you decided which license you are releasing the project under yet? 

Thanks!

**Comment by bpfz** [comment]
Hey!
I've tried to make it easy to understand and to make it easy for others to make changes they see fit so I hope you find it that way as well :+1:. I added a License.md (http://unlicense.org/) to the project. It will be fun to see what you create out of it!

Happy coding.

**Comment by jbellmore** [comment]
That's great, thanks so much! Look forward to contributing.
